### ISSUE TITLE
Not able to search ".nes" files present in internal storage of Sony Bravia 8200e android TV.

### ISSUE THREAD

**Issue by Vijay053** [retrograde/retrograde-android#32]
Hi,
I copied few .nes files into download folder of my android Tv internal storage. They are not listing in the RetroGrade app. I have tried all the options from app and given appropriate permission also to it.

**Comment by codebutler** [comment]
The current version only looks for files in the root external storage directory (/sdcard) so it won't find things inside "Downloads". I'll fix this for the next update.
